language: ruby
rvm:
  - 2.5   # This must match https://pages.github.com/versions/
script: bundle exec rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

sudo: false   # faster build with container-based infra
addons:
  apt:
    packages:
      - libcurl4-openssl-dev  # Typhoeus depends on libcurl

# This caches the gem installation by using Bundler's cache.
cache: bundler