# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://aaronloo.com"
description: >- # this means to ignore newlines until next key
  aaronloo's personal home page with latest projects, exploits and discoveries.
biography: >-
  Aaron Loo is a modern day alchemist. By leveraging technology and empowering
  people, he transforms abstract thought into concrete action to deliver high business
  value.

  All content is solely based off the author's opinions, and not representative of
  the company of employment.

# build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from    # allows custom redirecting with front-matter `redirect_from` key
sass:
  style: compressed
permalink: /:categories/:title

google_analytics: UA-132387320-1

# Used with Jekyll SEO plugin (comes default with github-pages)
title: aaronloo.com
social:
  name: Aaron Loo
  links:
    - https://github.com/domanchi
    - https://linkedin.com/in/aaronloo/